name: MobRemover
version: '1.0.0'
main: org.laceperro.MobRemover
api-version: 1.19
authors: [ Serbob, kmunoz99 ]
description: A plugin that enables/disables the spawn of Mobs. Based on PhantomRemover by Serbob
commands:
  mobs:
    description: Enables/disables the spawn of mobs.